swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8181'
basePath: /
tags:
  - name: product-controller
    description: Product Controller
  - name: category-controller
    description: Category Controller
paths:
  /category:
    get:
      tags:
        - category-controller
      summary: getCategories
      operationId: getCategoriesUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: pageable
          description: pageable
          required: false
          schema:
            $ref: '#/definitions/Pageable'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Page«Category»'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/category/{categoryName}/products':
    get:
      tags:
        - category-controller
      summary: findByCategoryName
      operationId: findByCategoryNameUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: categoryName
          in: path
          description: categoryName
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/category/{parentCategoryId}/category':
    post:
      tags:
        - category-controller
      summary: createCategory
      operationId: createCategoryUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: parentCategoryId
          in: path
          description: parentCategoryId
          required: true
          type: integer
          format: int64
        - in: body
          name: category
          description: category
          required: true
          schema:
            $ref: '#/definitions/Category'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Category'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /product:
    post:
      tags:
        - product-controller
      summary: createProduct
      operationId: createProductUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: product
          description: product
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Product'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /products:
    get:
      tags:
        - product-controller
      summary: getProducts
      operationId: getProductsUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: pageable
          description: pageable
          required: false
          schema:
            $ref: '#/definitions/Pageable'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Page«Product»'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  ProductSku:
    type: object
    properties:
      baseunitPrice:
        type: string
      descritpion:
        type: string
      discount:
        $ref: '#/definitions/Discount'
      fulfillment:
        $ref: '#/definitions/Fulfillment'
      id:
        type: integer
        format: int64
      inventoryType:
        type: string
      isActive:
        type: boolean
      isAvailable:
        type: boolean
      isSubscription:
        type: boolean
      media:
        type: array
        items:
          $ref: '#/definitions/Media'
      name:
        type: string
      productType:
        type: string
      qtyAvailable:
        type: integer
        format: int32
      retailPrice:
        type: number
        format: double
      salePrice:
        type: number
        format: double
      shortDesc:
        type: string
      startDate:
        type: string
        format: date-time
      taxCode:
        type: string
      wwSku:
        type: string
  Fulfillment:
    type: object
    properties:
      friendlyName:
        type: string
      id:
        type: integer
        format: int64
      type:
        type: string
  Category:
    type: object
    properties:
      active:
        type: boolean
      featured:
        type: boolean
      id:
        type: integer
        format: int64
      isActive:
        type: boolean
      isFeatured:
        type: boolean
      isNavigationIncluded:
        type: boolean
      name:
        type: string
      navigationIncluded:
        type: boolean
      url:
        type: string
      urlKey:
        type: string
  Discount:
    type: object
    properties:
      amount:
        type: number
        format: double
  Pageable:
    type: object
    properties:
      offset:
        type: integer
        format: int64
      pageNumber:
        type: integer
        format: int32
      pageSize:
        type: integer
        format: int32
      paged:
        type: boolean
      sort:
        $ref: '#/definitions/Sort'
      unpaged:
        type: boolean
  Page«Product»:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/Product'
      empty:
        type: boolean
      first:
        type: boolean
      last:
        type: boolean
      number:
        type: integer
        format: int32
      numberOfElements:
        type: integer
        format: int32
      pageable:
        $ref: '#/definitions/Pageable'
      size:
        type: integer
        format: int32
      sort:
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
      totalPages:
        type: integer
        format: int32
  Currency:
    type: object
    properties:
      name:
        type: string
  Media:
    type: object
    properties:
      altText:
        type: string
      id:
        type: integer
        format: int64
      url:
        type: string
  Product:
    type: object
    properties:
      category:
        $ref: '#/definitions/Category'
      currency:
        $ref: '#/definitions/Currency'
      description:
        type: string
      discount:
        $ref: '#/definitions/Discount'
      id:
        type: integer
        format: int64
      isActive:
        type: boolean
      isNew:
        type: boolean
      medias:
        type: array
        items:
          $ref: '#/definitions/Media'
      name:
        type: string
      retailPrice:
        type: number
        format: double
      salePrice:
        type: number
        format: double
      skus:
        type: array
        items:
          $ref: '#/definitions/ProductSku'
      url:
        type: string
  Sort:
    type: object
    properties:
      empty:
        type: boolean
      sorted:
        type: boolean
      unsorted:
        type: boolean
  Page«Category»:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/Category'
      empty:
        type: boolean
      first:
        type: boolean
      last:
        type: boolean
      number:
        type: integer
        format: int32
      numberOfElements:
        type: integer
        format: int32
      pageable:
        $ref: '#/definitions/Pageable'
      size:
        type: integer
        format: int32
      sort:
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
      totalPages:
        type: integer
        format: int32
